# Generated by Django 5.2 on 2025-05-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedaudio",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
