# Generated by Django 5.2 on 2025-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_generatedaudio_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
