# Generated by Django 5.2 on 2025-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chathistory_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedaudio",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
